CREATE TABLE public.state_race_counts (
    id serial,
    date date NOT NULL,
    count_aian integer,
    tested_aian integer,
    deaths_aian integer,
    count_asian integer,
    tested_asian integer,
    deaths_asian integer,
    count_black integer,
    tested_black integer,
    deaths_black integer,
    count_hispanic integer,
    tested_hispanic integer,
    deaths_hispanic integer,
    count_leftblank integer,
    tested_leftblank integer,
    deaths_leftblank integer,
    count_nhpi integer,
    tested_nhpi integer,
    deaths_nhpi integer,
    count_other integer,
    tested_other integer,
    deaths_other integer,
    count_white integer,
    tested_white integer,
    deaths_white integer
);
ALTER TABLE ONLY public.state_race_counts
    ADD CONSTRAINT state_race_counts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_race_counts
    ADD CONSTRAINT state_race_counts_date_key UNIQUE (date);

CREATE TABLE public.state_age_counts (
    id serial,
    date date NOT NULL,
    count_unknown integer,
    tested_unknown integer,
    deaths_unknown integer,
    count_less_than_20 integer,
    tested_less_than_20 integer,
    deaths_less_than_20 integer,
    count_20_to_29 integer,
    tested_20_to_29 integer,
    deaths_20_to_29 integer,
    count_30_to_39 integer,
    tested_30_to_39 integer,
    deaths_30_to_39 integer,
    count_40_to_49 integer,
    tested_40_to_49 integer,
    deaths_40_to_49 integer,
    count_50_to_59 integer,
    tested_50_to_59 integer,
    deaths_50_to_59 integer,
    count_60_to_69 integer,
    tested_60_to_69 integer,
    deaths_60_to_69 integer,
    count_70_to_79 integer,
    tested_70_to_79 integer,
    deaths_70_to_79 integer,
    count_80_or_more integer,
    tested_80_or_more integer,
    deaths_80_or_more integer
);
ALTER TABLE ONLY public.state_age_counts
    ADD CONSTRAINT state_age_counts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_age_counts
    ADD CONSTRAINT state_age_counts_date_key UNIQUE (date);

CREATE TABLE public.state_age_race_counts (
    id serial,
    date date NOT NULL,
    count_unknown_aian integer,
    tested_unknown_aian integer,
    deaths_unknown_aian integer,
    count_less_than_20_aian integer,
    tested_less_than_20_aian integer,
    deaths_less_than_20_aian integer,
    count_20_to_29_aian integer,
    tested_20_to_29_aian integer,
    deaths_20_to_29_aian integer,
    count_30_to_39_aian integer,
    tested_30_to_39_aian integer,
    deaths_30_to_39_aian integer,
    count_40_to_49_aian integer,
    tested_40_to_49_aian integer,
    deaths_40_to_49_aian integer,
    count_50_to_59_aian integer,
    tested_50_to_59_aian integer,
    deaths_50_to_59_aian integer,
    count_60_to_69_aian integer,
    tested_60_to_69_aian integer,
    deaths_60_to_69_aian integer,
    count_70_to_79_aian integer,
    tested_70_to_79_aian integer,
    deaths_70_to_79_aian integer,
    count_80_or_more_aian integer,
    tested_80_or_more_aian integer,
    deaths_80_or_more_aian integer,
    count_unknown_asian integer,
    tested_unknown_asian integer,
    deaths_unknown_asian integer,
    count_less_than_20_asian integer,
    tested_less_than_20_asian integer,
    deaths_less_than_20_asian integer,
    count_20_to_29_asian integer,
    tested_20_to_29_asian integer,
    deaths_20_to_29_asian integer,
    count_30_to_39_asian integer,
    tested_30_to_39_asian integer,
    deaths_30_to_39_asian integer,
    count_40_to_49_asian integer,
    tested_40_to_49_asian integer,
    deaths_40_to_49_asian integer,
    count_50_to_59_asian integer,
    tested_50_to_59_asian integer,
    deaths_50_to_59_asian integer,
    count_60_to_69_asian integer,
    tested_60_to_69_asian integer,
    deaths_60_to_69_asian integer,
    count_70_to_79_asian integer,
    tested_70_to_79_asian integer,
    deaths_70_to_79_asian integer,
    count_80_or_more_asian integer,
    tested_80_or_more_asian integer,
    deaths_80_or_more_asian integer,
    count_unknown_black integer,
    tested_unknown_black integer,
    deaths_unknown_black integer,
    count_less_than_20_black integer,
    tested_less_than_20_black integer,
    deaths_less_than_20_black integer,
    count_20_to_29_black integer,
    tested_20_to_29_black integer,
    deaths_20_to_29_black integer,
    count_30_to_39_black integer,
    tested_30_to_39_black integer,
    deaths_30_to_39_black integer,
    count_40_to_49_black integer,
    tested_40_to_49_black integer,
    deaths_40_to_49_black integer,
    count_50_to_59_black integer,
    tested_50_to_59_black integer,
    deaths_50_to_59_black integer,
    count_60_to_69_black integer,
    tested_60_to_69_black integer,
    deaths_60_to_69_black integer,
    count_70_to_79_black integer,
    tested_70_to_79_black integer,
    deaths_70_to_79_black integer,
    count_80_or_more_black integer,
    tested_80_or_more_black integer,
    deaths_80_or_more_black integer,
    count_unknown_hispanic integer,
    tested_unknown_hispanic integer,
    deaths_unknown_hispanic integer,
    count_less_than_20_hispanic integer,
    tested_less_than_20_hispanic integer,
    deaths_less_than_20_hispanic integer,
    count_20_to_29_hispanic integer,
    tested_20_to_29_hispanic integer,
    deaths_20_to_29_hispanic integer,
    count_30_to_39_hispanic integer,
    tested_30_to_39_hispanic integer,
    deaths_30_to_39_hispanic integer,
    count_40_to_49_hispanic integer,
    tested_40_to_49_hispanic integer,
    deaths_40_to_49_hispanic integer,
    count_50_to_59_hispanic integer,
    tested_50_to_59_hispanic integer,
    deaths_50_to_59_hispanic integer,
    count_60_to_69_hispanic integer,
    tested_60_to_69_hispanic integer,
    deaths_60_to_69_hispanic integer,
    count_70_to_79_hispanic integer,
    tested_70_to_79_hispanic integer,
    deaths_70_to_79_hispanic integer,
    count_80_or_more_hispanic integer,
    tested_80_or_more_hispanic integer,
    deaths_80_or_more_hispanic integer,
    count_unknown_leftblank integer,
    tested_unknown_leftblank integer,
    deaths_unknown_leftblank integer,
    count_less_than_20_leftblank integer,
    tested_less_than_20_leftblank integer,
    deaths_less_than_20_leftblank integer,
    count_20_to_29_leftblank integer,
    tested_20_to_29_leftblank integer,
    deaths_20_to_29_leftblank integer,
    count_30_to_39_leftblank integer,
    tested_30_to_39_leftblank integer,
    deaths_30_to_39_leftblank integer,
    count_40_to_49_leftblank integer,
    tested_40_to_49_leftblank integer,
    deaths_40_to_49_leftblank integer,
    count_50_to_59_leftblank integer,
    tested_50_to_59_leftblank integer,
    deaths_50_to_59_leftblank integer,
    count_60_to_69_leftblank integer,
    tested_60_to_69_leftblank integer,
    deaths_60_to_69_leftblank integer,
    count_70_to_79_leftblank integer,
    tested_70_to_79_leftblank integer,
    deaths_70_to_79_leftblank integer,
    count_80_or_more_leftblank integer,
    tested_80_or_more_leftblank integer,
    deaths_80_or_more_leftblank integer,
    count_unknown_nhpi integer,
    tested_unknown_nhpi integer,
    deaths_unknown_nhpi integer,
    count_less_than_20_nhpi integer,
    tested_less_than_20_nhpi integer,
    deaths_less_than_20_nhpi integer,
    count_20_to_29_nhpi integer,
    tested_20_to_29_nhpi integer,
    deaths_20_to_29_nhpi integer,
    count_30_to_39_nhpi integer,
    tested_30_to_39_nhpi integer,
    deaths_30_to_39_nhpi integer,
    count_40_to_49_nhpi integer,
    tested_40_to_49_nhpi integer,
    deaths_40_to_49_nhpi integer,
    count_50_to_59_nhpi integer,
    tested_50_to_59_nhpi integer,
    deaths_50_to_59_nhpi integer,
    count_60_to_69_nhpi integer,
    tested_60_to_69_nhpi integer,
    deaths_60_to_69_nhpi integer,
    count_70_to_79_nhpi integer,
    tested_70_to_79_nhpi integer,
    deaths_70_to_79_nhpi integer,
    count_80_or_more_nhpi integer,
    tested_80_or_more_nhpi integer,
    deaths_80_or_more_nhpi integer,
    count_unknown_other integer,
    tested_unknown_other integer,
    deaths_unknown_other integer,
    count_less_than_20_other integer,
    tested_less_than_20_other integer,
    deaths_less_than_20_other integer,
    count_20_to_29_other integer,
    tested_20_to_29_other integer,
    deaths_20_to_29_other integer,
    count_30_to_39_other integer,
    tested_30_to_39_other integer,
    deaths_30_to_39_other integer,
    count_40_to_49_other integer,
    tested_40_to_49_other integer,
    deaths_40_to_49_other integer,
    count_50_to_59_other integer,
    tested_50_to_59_other integer,
    deaths_50_to_59_other integer,
    count_60_to_69_other integer,
    tested_60_to_69_other integer,
    deaths_60_to_69_other integer,
    count_70_to_79_other integer,
    tested_70_to_79_other integer,
    deaths_70_to_79_other integer,
    count_80_or_more_other integer,
    tested_80_or_more_other integer,
    deaths_80_or_more_other integer,
    count_unknown_white integer,
    tested_unknown_white integer,
    deaths_unknown_white integer,
    count_less_than_20_white integer,
    tested_less_than_20_white integer,
    deaths_less_than_20_white integer,
    count_20_to_29_white integer,
    tested_20_to_29_white integer,
    deaths_20_to_29_white integer,
    count_30_to_39_white integer,
    tested_30_to_39_white integer,
    deaths_30_to_39_white integer,
    count_40_to_49_white integer,
    tested_40_to_49_white integer,
    deaths_40_to_49_white integer,
    count_50_to_59_white integer,
    tested_50_to_59_white integer,
    deaths_50_to_59_white integer,
    count_60_to_69_white integer,
    tested_60_to_69_white integer,
    deaths_60_to_69_white integer,
    count_70_to_79_white integer,
    tested_70_to_79_white integer,
    deaths_70_to_79_white integer,
    count_80_or_more_white integer,
    tested_80_or_more_white integer,
    deaths_80_or_more_white integer
);
ALTER TABLE ONLY public.state_age_race_counts
    ADD CONSTRAINT state_age_race_counts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_age_race_counts
    ADD CONSTRAINT state_age_race_counts_date_key UNIQUE (date);

CREATE TABLE public.state_gender_counts (
    id serial,
    date date NOT NULL,
    count_female integer,
    tested_female integer,
    deaths_female integer,
    count_male integer,
    tested_male integer,
    deaths_male integer,
    count_unknownleftblank integer,
    tested_unknownleftblank integer,
    deaths_unknownleftblank integer
);
ALTER TABLE ONLY public.state_gender_counts
    ADD CONSTRAINT state_gender_counts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_gender_counts
    ADD CONSTRAINT state_gender_counts_date_key UNIQUE (date);

CREATE TABLE public.state_testing_results (
    id serial,
    date date NOT NULL,
    total_tested integer NOT NULL,
    confirmed_cases integer NOT NULL,
    deaths integer NOT NULL
);
ALTER TABLE ONLY public.state_testing_results
    ADD CONSTRAINT state_testing_results_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_testing_results
    ADD CONSTRAINT state_testing_results_date_key UNIQUE (date);

CREATE TABLE public.state_recovery_data (
    id serial,
    report_date date NOT NULL,
    sample_surveyed integer,
    recovered_cases integer,
    recovered_and_deceased_cases integer,
    recovery_rate numeric
);
ALTER TABLE ONLY public.state_recovery_data
    ADD CONSTRAINT state_recovery_data_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_recovery_data
    ADD CONSTRAINT state_recovery_data_report_date_key UNIQUE (report_date);

CREATE TABLE public.state_probable_case_counts (
    id serial,
    date date NOT NULL,
    probable_cases integer,
    probable_deaths integer
);
ALTER TABLE ONLY public.state_probable_case_counts
    ADD CONSTRAINT state_probable_case_counts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.state_probable_case_counts
    ADD CONSTRAINT state_probable_case_counts_date_key UNIQUE (date);
